class Interests {
  static const list = <String>[
    'Technology',
    'Travel',
    'Photography',
    'Cooking',
    'Fashion',
    'Sports',
    'Fitness',
    'Art',
    'Music',
    'Movies',
    'Reading',
    'Writing',
    'Science',
    'Nature',
    'Gardening',
    'Astronomy',
    'History',
    'Psychology',
    'Philosophy',
    'DIY/Crafts',
    'Gaming',
    'Hiking',
    'Meditation',
    'Health and Wellness',
    'Coding/Programming',
    'Graphic Design',
    'Business',
    'Finance',
    'Foodie',
    'Yoga',
    'Education',
    'Languages',
    'Animals/Pets',
    'Social Justice',
    'Volunteer Work',
    'Home Decor',
    'Cars/Automobiles',
    'Dancing',
    'Collecting',
    'Magic/Illusions',
  ];
}
